# COMPARISON OPERATORS
_this is my practice file for lecture three (Comparison operators)._

## NUMPY RECAP

In [33]:
import numpy as np
np_height = np.array([1.73, 1.68, 1.71, 1.89, 1.79])
np_weight = np.array([65.4, 59.2, 63.6, 88.4, 68.7])
bmi = np_weight/np_height **2

In [34]:
bmi

array([21.85171573, 20.97505669, 21.75028214, 24.7473475 , 21.44127836])

In [35]:
bmi > 23

array([False, False, False,  True, False])

In [36]:
bmi[bmi>23]

array([24.7473475])

## NUMERIC COMPARISON

In [37]:
2 < 3


True

In [38]:
x, y = 2, 5
x > y

False

In [39]:
bmi > 21

array([ True, False,  True,  True,  True])

In [40]:
hi_bmi = bmi > 21

In [41]:
bmi[hi_bmi]

array([21.85171573, 21.75028214, 24.7473475 , 21.44127836])

## NUMPY

**Logical_and()**
**logical_or()**
**logical_not()**

In [42]:
np.logical_and(bmi >21, bmi < 22)

array([ True, False,  True, False,  True])

In [43]:
bmi[np.logical_and(bmi >21, bmi < 22)]

array([21.85171573, 21.75028214, 21.44127836])

## if

In [44]:
z =4
if z % 2 == 0:
    print("z is even")

z is even


In [45]:
z = 4
if z % 2 == 0:
    print("checking " + str(z))
    print("z is even")

checking 4
z is even


### Elif

In [46]:
z = 3
if z % 2 == 0:
    print("z is divisible by 2")
elif z % 3 == 0:
    print("z is divisible by 3")
else:
    print("z is neither divisible by 2 nor 3")

z is divisible by 3


## Filtering pandas DataFrames

In [47]:
import pandas as pd 
brics = pd.read_csv("brics.csv")


In [48]:
brics

Unnamed: 0       country    capital    area  population
0         BR        Brazil   Brazilia   8.516      200.40
1         RU        Russia     Moscow  17.100      143.50
2         IN         India  New Delhi   3.286     1252.00
3         CH         China    Beijing   9.597     1357.00
4         SA  South Africa   Pretoria   1.221       52.98

In [49]:
brics = pd.read_csv("brics.csv", index_col= 0)
brics

country    capital    area  population
BR        Brazil   Brazilia   8.516      200.40
RU        Russia     Moscow  17.100      143.50
IN         India  New Delhi   3.286     1252.00
CH         China    Beijing   9.597     1357.00
SA  South Africa   Pretoria   1.221       52.98

  *select countries with area over 8 million km2*

  this involves three steps
  1. select area column
  2. Do comparison on area column
  3. use the result to select countries

#### Step 1 : Get column

In [50]:
brics["area"]

BR     8.516
RU    17.100
IN     3.286
CH     9.597
SA     1.221
Name: area, dtype: float64

In [51]:
#Alternatives
brics.loc[:, 'area']

BR     8.516
RU    17.100
IN     3.286
CH     9.597
SA     1.221
Name: area, dtype: float64

In [52]:
brics.iloc[:, 2]

BR     8.516
RU    17.100
IN     3.286
CH     9.597
SA     1.221
Name: area, dtype: float64

### step 2: Compare

In [53]:
brics['area'] > 8

BR     True
RU     True
IN    False
CH     True
SA    False
Name: area, dtype: bool

In [54]:
is_huge = brics.iloc[:, 2] > 8

### Step 3: subset DF

In [55]:
is_huge

BR     True
RU     True
IN    False
CH     True
SA    False
Name: area, dtype: bool

In [56]:
brics[is_huge]

country   capital    area  population
BR  Brazil  Brazilia   8.516       200.4
RU  Russia    Moscow  17.100       143.5
CH   China   Beijing   9.597      1357.0

In [57]:
brics[brics['area'] > 8]

country   capital    area  population
BR  Brazil  Brazilia   8.516       200.4
RU  Russia    Moscow  17.100       143.5
CH   China   Beijing   9.597      1357.0

### Boolean operators

In [58]:
np.logical_and(brics['area'] > 8, brics['area'] < 10)

BR     True
RU    False
IN    False
CH     True
SA    False
Name: area, dtype: bool

In [59]:
brics[np.logical_and(brics['area'] > 8, brics['area'] < 10)]

country   capital   area  population
BR  Brazil  Brazilia  8.516       200.4
CH   China   Beijing  9.597      1357.0

# THE END