# NUMPY

In [1]:
import numpy as np

baseball = [180, 215, 210, 210, 188, 176, 209, 200]

#create numpy array from baseball as np_baseball
np_baseball = np.array(baseball)

print(np_baseball)
print(type(np_baseball))

[180 215 210 210 188 176 209 200]
<class 'numpy.ndarray'>


In [2]:
np1 = np.array([0,1,2,3,4,5,6,7,8,9])
print(np1)
print(np1.shape)

[0 1 2 3 4 5 6 7 8 9]
(10,)


In [3]:
#Range
np2 = np.arange(10)
print(np2)

[0 1 2 3 4 5 6 7 8 9]


In [4]:
#step
np3 = np.arange(0,10,2)
print(np3)

[0 2 4 6 8]


## slicing 1D array

In [5]:
np1 = np.arange(10)
print(np1[:4])


[0 1 2 3]


In [6]:
#return 3 - 8
print(np1[3:9])

[3 4 5 6 7 8]


In [7]:

#return 2 - 8 in 2 step
print(np1[2:9:2])

[2 4 6 8]


## slicing 2D array

In [10]:
np2 = np.array([[1,2,3,4,5], [6,7,8,9,10]])
# pull.out.single.element
print(np2[0,1])
print(np2[0,3])

2
4


In [12]:
# pull.out.entire.first row
print(np2[0,:])
print(f"The entire third colum is: {np2[:,2]}")

[1 2 3 4 5]
The entire third colum is: [3 8]
